[project]
name = "salla_client"
authors = [
    { name = "Golive-Solutions", email = "info@golive-solutions.com"}
]
description = "Salla Client"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "salla-common-lib>=0.0.12",
    "requests>=2.31.0",
    "python-dateutil>=2.8.2",
    "PyJWT>=2.8.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

### These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
### package_name = "~=1.1.0"
